name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Setup directories
        run: mkdir -p ros2_ws/src
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src/drobo_interfaces

      - name: Install dependencies
        run: |
          rosdep update && 
          apt-get update && 
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Build tests
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
